### ISSUE TITLE
Renombrar proyecto: [UELA x VIA]

### ISSUE THREAD

**Issue by VIA-GlaciaR** [VIA-GlaciaR/VIA-GlaciaR.github.io#1]
Renombrar Poryecto UELA x VIA

Impacta en Releases Upsala, Viedma, 
Tanto Front y Back
Además de los ciclos de CI/CD

- [x]  PabloEzequiel/VIA-Upsala#22
- [x] PabloEzequiel/VIA-Upsala-backend#1 

- [x] PabloEzequiel/VIA-Viedma#3
- [x] PabloEzequiel/VIA-Viedma-backend#1

**Comment by VIA-GlaciaR** [comment]
Renombre sus cuatro tareas dependidentes a "VIA" aunque lo voy a cambiar a "GlaciaR" como se ve en la próxima sub-tarea en curso
